const localizations = [];

localizations["he"] = [];
const hebrew = localizations["he"];
hebrew["kapot"] = "בית כנסת כפות תמרים"
hebrew["address"] = "הציפורן 5, אפרת"
hebrew["date"] = 'אלול, תשפ"ד'
hebrew["dear"] = 'משפחת כפות תמרים היקרה,'
hebrew["intro"] = 'לקראת ראש השנה הבא עלינו לטובה, אנו מאחלים לכולם שנה של בריאות, אושר וצמיחה רוחנית, כיחידים וביחד כקהילה. אנו גם רוצים לנצל את ההזדמנות לברך את כל אלה שהצטרפו לאחרונה לשכונה! אנו מקווים שתמצאו בבית הכנסת משפחה שנייה וחמה.'
hebrew["outstanding"] = 'עם סגירת השנה, אנו מבקשים מכל החברים הנוכחיים לדאוג לכל התחייבויות שטרם נותרו (עמלות או עמלות קודמים וכו׳) באמצעות <a href="https://ktefrat.org.il/donate/" target="_blank">קישור זה</a>. אם נתת חסות לקדיש בשנה האחרונה, אנא וודא ששילמת לישראל כהן. תודה!'
hebrew["membershipTitle"] = "חֲבֵרוּת"
hebrew["fees"] = "דמי חברות הן כדלקמן:"
hebrew["membershipFeeFull"] = "חברי קרן בנין: <strong>800&#8362;</strong> (למשפחה)"
hebrew["membershipFeePartial"] = "חברים שנתיים: <strong>1,100&#8362;</strong> (למשפחה)"
hebrew["membershipFeeWeekday"] = "תפילות ימי חול (ללא חברות): <strong>600&#8362;</strong>"
hebrew["infoForm"] = 'כל החברים, החדשים והוותיקים מתבקשים למלא <a href="https://ktefrat.org.il/memberform/" target="_blank">טופס זה</a> אם טרם עשו זאת.'
hebrew["negotiable"] = 'נשמח לקבל אותכם כחברים בקהילה שלנו. במידה ויש לכם אילוצים כספיים, אפשר לדבר עם אריאל אומן (<a href="mailto:arielauman@gmail.com" target="_blank">arielauman@gmail.com</a>)  בסודיות.'
hebrew['buildingFundHeader'] = 'קרן בנין'
hebrew['buildingFundAmount'] = 'קרן בנין היא <strong>3,600&#8362;</strong>. תשלומי קרן בנין יכולים להתבצע בתשלומים, במינימום של 360 ₪ לשנה. אפשר לבצע תשלומים לקרן בנין <a href="https://pay.hyp.co.il/cgi-bin/yaadpay/yaadpay3ds.pl?Amount=3600&Coin=1&FixTash=False&Info=Building%20Fund&Masof=4501681128&MoreData=True&PageLang=ENG&Postpone=False&SendHesh=True&ShowEngTashText=True&Tash=1&UTF8out=True&action=pay&freq=1&sendemail=True&tmp=11&signature=9a82bde4c243551ccdee8592b0379c75490991da45996eade5c68bfc2e6ac414" target="_blank">בקישור זה</a>.'
hebrew['seating'] = 'מקומות ישיבה לימים נוראים'
hebrew['terms'] = 'החברות כוללת מקומות ישיבה לבני המשפחה הקרובים. מקומות ישיבה לילדים נשואים, הורים, סבים וסבתות ואורחים אחרים הם <strong>150&#8362;/מושב</strong> לימים נוראים ו-<strong>100&#8362;/מושב</strong> לראש השנה או ליום כיפור. מקומות ישיבה נוספים תלויים בזמינות. מקומות ישיבה לילדים מתחת לכיתה ה׳ יהיו בהתאם לזמינות. <strong>בשנה שעברה היו לנו עודף בקשות למקומות ישיבה בעזרת נשים ואז נשים רבות לא הגיעו לתפילות. אנו מבקשים מכולם להיות מודעים למגבלות המקום. <u>נא לא לבקש יותר מושבים ממה שאתה באמת צריך.</u></strong>'
hebrew['deadline'] = 'להזמין מקומות יש למלא את טופס למטה (לא נקבל בקשות מקומות בכל דרך אחרת) בהקדם האפשרי. המועד האחרון להזמנת מקומות הוא יום ראשון, 15.9.2024 / י"ב אלול.'
hebrew['methods'] = 'אנא עשה כל מאמץ לשלם באמצעות הקישורים שכבר סופקו. למי שזקוק לשיטת תשלום אחרת, תוכל להשתמש באפשרויות הבאות:'
hebrew['methodLink'] = '<strong>מועדף</strong>: אתר הבית כנסת: <a href="https://ktefrat.org.il/donate/" target="_blank">https://ktefrat.org.il/donate/</a>'
hebrew['methodBank'] = 'העברה בנקאית:'
hebrew['accountName'] = 'שם חשבון: בית הכנסת כפות תמרים'
hebrew['bankName'] = 'בנק: מזרחי 20'
hebrew['branch'] = 'סניף: אפרת 454'
hebrew['accountNumber'] = 'מספר חשבון: 149924'
hebrew['check'] = "צ'ק לכפות תמרים"
hebrew['thanks'] = 'תודה מראש על התייחסותכם המהירה לעניין זה.'
hebrew['signature'] = 'ועד מנהל של כפות תמרים'
hebrew['requests'] = 'בקשות למושבים בימים נוראים'
hebrew['nameTitle'] = 'שם'
hebrew['emailTitle'] = 'מייל'
hebrew['memberTitle'] = 'מצב חברות'
hebrew['fullMember'] = 'קרן בנין שולם; משלם דמי חברות שנתיים'
hebrew['becomingFullMember'] = 'קרן בנין טרם שולם; משלם אותו כעת עם דמי חברות שנתיים'
hebrew['partialMember'] = 'משלם דמי חברות שנתיים, אבל לא קרן בנין'
hebrew['notAMember'] = 'עוד לא מצטרף לחברות בית הכנסת; רוצה רק מושבים'
hebrew['numDavenersTitle'] = 'סה״כ מתפללים במשך ימים נוראים'
hebrew['contact'] = 'לשאלות או הערות, נא ליצור קשר עם <a href="mailto:ktefrat@gmail.com" target="_blank">ktefrat@gmail.com</a>.'
hebrew['davenerTitleStart'] = 'מתפלל #'
hebrew['maleLabelX'] = 'זכר'
hebrew['femaleLabelX'] = 'נקבה'
hebrew['optionType'] = 'קטגוריה'
hebrew['optionMember'] = 'חבר'
hebrew['optionYoungKid'] = 'ילד מתחת לכיתה ה׳'
hebrew['optionOldKid'] = 'ילד - כיתה ה׳ ומעלה'
hebrew['optionGuest'] = 'ילד נשוי / אורח'
hebrew['roshHaShanahLabelX'] = 'ראש השנה'
hebrew['yomKippurLabelX'] = 'יום כיפור'
hebrew['due'] = 'לתשלום:'
hebrew['totalsDue'] = 'סכומים לתשלום'
hebrew['eachLink'] = 'נא לשלם כל סכום בקישור המתאים.'
hebrew['membershipDueLabel'] = 'תשלום שנתי'
hebrew['buildingFundDueLabel'] = 'קרן בנין'
hebrew['seatsDueLabel'] = 'תשלום למושבים'
hebrew['submitButton'] = 'שלח'
hebrew['name'] = 'שם'
hebrew['optionGrade'] = 'כיתה'
hebrew['optionGan'] = 'גן'
hebrew['optionFirst'] = 'א׳'
hebrew['optionSecond'] = 'ב׳'
hebrew['optionThird'] = 'ג׳'
hebrew['optionFourth'] = 'ד׳'
hebrew['notesTitle'] = 'הערות'
hebrew['thankyou'] = 'תודה!'
hebrew['weekdayDavener'] = 'מתפלל ימי חול'